### ISSUE TITLE
which version of midi in the website is this?

### ISSUE THREAD

**Issue by faltings** [paulhutchings/international-e-piano-dataset#1]
Hello,

Seen from https://forum.pianoworld.com/ubbthreads.php/topics/670559/international-piano-e-competition-midi-files.html
"There are three versions of the midi files but you will most likely want to go with the "Enhanced MIDI" versions for compatibility."

Since [the ](https://piano-e-competition.com/) is not available now, I wonder your version
- they are different from the ones in https://magenta.tensorflow.org/datasets/maestro

Many Thanks!

**Comment by studioph** [comment]
To be honest, I have no idea. I uploaded these years ago while I was working on a project using them, but I didn't even remember there were multiple variants of the MIDI files. You could try seeing if the Internet Archive has anything saved from the site and possibly compare them with these? Wish I had more info for you :(

**Comment by faltings** [comment]
That's very helpful- I found some of different versions on Internet Archive.
